10 CLS
20 COLOR 18
30 PRINT "Crimelab                                                                Crimelab"
40 COLOR 7
50 PRINT "A lesson in:                                                        A lesson in:"
60 COLOR 12
70 PRINT "                                 Blood Typing"
80 PRINT ""
90 COLOR 7
100 PRINT "Press any key to continue."
110 COLOR 0
120 INPUT A$
130 COLOR 7
140 CLS
150 PRINT "Oh, No!!!!! The ''Mona Data'' has been stolen from the museum!"
160 PRINT "It is the only painting with blinking eyes! See??"
170 COLOR 31
180 PRINT "ø ø"
190 COLOR 7
200 PRINT "Luckily, the culprit left a drop of blood on the glass that he broke!"

