CLS
PLAY "T108 O3"

PRINT "Just sit right back and you'll hear a tale"
PLAY "L4 A L8 D L16 A P16 A P16 AAG P16 E P16 L8 C P16"
PRINT "A tale of a fateful trip"
PLAY "L16 C L8 D L16 A P16 A P16 A P16 L4 G P8"
PRINT "That started from this tropic port"
PLAY "L16 A P16 L8 D L16 A P16 A P16 AAG P16 >C P16 L8 C<"
PRINT "Aboard this tiny ship.": PRINT ""
PLAY "L16 G P16 L8 F. P16 L8 E L16 C P16 L4 D P8"

PRINT "The mate was a mighty sailin' man"
PLAY "L16 D P16 L8 E- L16 B- P16 B- P16 B- B- G# P16 F P16 L8 C# P16"
PRINT "The skipper brave and sure"
PLAY "L16 C# L8 E- L16 B- P16 B- P16 B- P16 L4 G# P8"
PRINT "Five passengers set sail that day"
PLAY "L16 B- P16 L8 E- L16 B- P16 B- P16 B- B- G# P16 >C# P16 L8 C#< L16 G# P16"
PRINT "For a three hour tour. ";
PLAY "L8 F#. P16 F L16 C# P16 L4 E- P8"
PRINT "(A three hour tour.)": PRINT ""
PLAY "L16 E- P16 L8 F#. P16 F L16 C# P16 L4 E- P1"

PRINT "The weather started getting rough"
PLAY "L4 E- L8 E L16 B P16 B P16 B B A P16 F# P16 L8 D P16"
PRINT "The tiny ship was tossed"
PLAY "L16 D L8 E L16 B P16 B P16 B P16 L4 A P8"
PRINT "If not for the courage of the fearless crew"
PLAY "L16 B P16 L8 E L16 B P16 B P16 B B A P16 >D P16 L8 D<"
PRINT "The Minnow would be lost. ";
PLAY "L16 A P16 G L8 G P16 F# L16 D P16 L4 E P8"
PRINT "(The Minnow would be lost.)": PRINT ""
PLAY "L16 E P16 G L8 G P16 L8 F# L16 D P16 L4 E P8"

PRINT "The ship set ground on the shore of this uncharted desert isle"
PLAY "L16 E P16 L8 F L16 >C P16 C P16 C C< B- P16 G P16 L8 E- P16"
PLAY "L16 E- L8 F L16 >C P16 C P16 C< P16 L4 B- P8"
PRINT "With Gilligan";
PLAY "L16 >C< P16 F >C L2 C< P4"
PRINT ", the Skipper, too"
PLAY "L8 G# L16 B- P16 E- P16 L2 E- P8"
PRINT "The millionaire";
PLAY "L16 E- P16 L8 F P16 >L16 C L4 C.< P8"
PRINT ", and his wife"
PLAY "L8 B- G# L2 B-. P8"
PRINT "The movie star";
PLAY "L16 G# P16 L8 F. P16 L16 >C P16 L4 C.< P8"
PRINT ", the professor and Mary Ann"
PLAY "L16 B- P16 F P16 F P16 L8 >C.< P16 L16 B- P16 B- P16 L8 >E-. P16"
PRINT "Here on Gilligan's Isle."
PLAY "F. P16 F. P16 L16 G P16 G P16 L8 E-. P16 L2 F.<"

