' plays the English song Greensleeves
COLOR 14, 2
CLS
PRINT "Greensleeves VERSE"
PRINT "Alas, my love, you do me wrong to cast me off discourteously. When"
PRINT "I have loved you so long delighting in your company."
PLAY "T100 O2 E G A MS B. >C< B MN A F# MS D. E F# MN G MS E E. D# E MN F#...."
PLAY "T100 O2 <B....> MS E MN G MS A B. >C< B MN A MS F# D. E F# G F# E D#. C#"
PLAY "T100 O2 D# MN E........ E..."
COLOR 1, 15
CLS
PRINT "Greensleeves REFRAIN"
PRINT "Greensleeves was all my joy. Greensleeves was my delight. Greensleeves"
PRINT "was my heart of gold, and who but lady Greensleeves."
PLAY "T100 O2 >D.. MS D.. C< B MN A MS F# D.. E F# MN G MS E E.. D# E MN F# MS"
PLAY "T100 O2 D# MN <B> >D.. MS D.. C< B MN A MS F# D.. E F# G F# E D#.. C# D#"
PLAT "T100 O2 MN E........ E..."
END

