CLS
RANDOMIZE TIMER
a% = INT(RND * 80) + 1
b% = INT(RND * 80) + 1
c% = INT(RND * 80) + 1
d% = INT(RND * 80) + 1
e% = INT(RND * 80) + 1
f% = INT(RND * 80) + 1
g% = INT(RND * 80) + 1
h% = INT(RND * 80) + 1
i% = INT(RND * 80) + 1
j% = INT(RND * 80) + 1
k% = INT(RND * 80) + 1
l% = INT(RND * 80) + 1
m% = INT(RND * 80) + 1
n% = INT(RND * 80) + 1
o% = INT(RND * 80) + 1
p% = INT(RND * 80) + 1
q% = INT(RND * 80) + 1
r% = INT(RND * 80) + 1
s% = INT(RND * 80) + 1
t% = INT(RND * 80) + 1
PRINT "Keno numbers:"
PRINT a%; b%; c%; d%; e%; f%; g%; h%; i%; j%; k%; l%; m%; n%; o%; p%; q%; r%; s%; t%

