CLS
PRINT "Swing your partner up and round, put him in the trash and stuff him down"
PLAY "T175 <<E C C <A> C C E.. E C C <A> C D C.."
PRINT "Swing your partner doe-sy-doe, drop an anvil on her toe"
PLAY "E C C <A> C C E.. E C C <A> C D C.."
PRINT "Then grab the nearest chair your able, then slam in on the nearest table"
PLAY "E C C <A> C C E.. E C C <A> C D C.."
PRINT " "
PRINT "See that guy with the mean ol' face, kick his butt all over the place"
PLAY "E C C <A> C C E.. E C C <A> C D C.."
PRINT "Punch him, slap him round and round, do it 'till his pants fall down"
PLAY "E C C <A> C C E.. E C C <A> C D C.."
PRINT "He's got funny underwear, everybody gawk and stare"
PLAY "E C C <A> C C E.. E C C <A> C D C.."
COLOR 4, 0
PRINT " "
PRINT "Rock it!!!!!!!!!!!!"
COLOR 7, 0
PLAY "T100 <A.. F.. C...."

