CLS
PRINT "            ÚÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄ¿  "
PRINT "            ³ ø ³  HP Thinkjet  ³ ø ³  "
PRINT "            ³ ø ³    2225 CD    ³ ø ³  "
PRINT "            ³ ø ³TEST:ABCDEFGHIJ³ ø ³  "
PRINT "            ³ ø ³KLMNOPQRSTUVWXY³ ø ³  "
PRINT "            ³ ø ³Z!@#$%^&*()_+-=³ ø ³  "
PRINT "            ³ ø ³`~1234567890,./³ ø ³  "
PRINT "            ³ ø ³<>?;:'[{]}\|abc³ ø ³  "
PRINT "            ³ ø ³defghijklmnopqr³ ø ³  "
PRINT "            ³ ø ³stuvwxyzûöñ«¬­þ³ ø ³  "
PRINT "          ÚÄÁÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÁÄ¿"

