CLS
PRINT "²²File²²Edit²²View²²Search²²Run²²Debug²²Options²²²²²²²²²²²²²²²²²²²²²²²²²²Help²²"
PRINT "ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Untitled²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿"
PRINT "³CLS                                                                          ²"
PRINT "³PRINT 'I love qbasic!!'                                                      ±"
PRINT "³END                                                                          ±"
PRINT "³                                                                             ±"
PRINT "³                                                                             ±"
PRINT "³                                                                             ±"
PRINT "³                                                                             ±"
PRINT "³                                                                             ±"
PRINT "³                                                                             ±"
PRINT "³                                                                             ±"
PRINT "³                                                                             ±"
PRINT "³                                                                             ±"
PRINT "³                                                                             ±"
PRINT "³                                                                             ±"
PRINT "³                                                                             ±"
PRINT "³                                                                             ±"
PRINT "³                                                                             ±"
PRINT "³                                                                             ±"
PRINT "³                                                                             ²"
PRINT "³²±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±²³"
PRINT "²²<Shift+F1=Help>²<F6=Window>²<F2=Subs>²<F5=Run>²<F8=Step>²²²²²³²²²N²00025:086²"
END












