' plays the Christmas song What Child is This?
COLOR 4, 2
CLS
PRINT "What Child is This? VERSE"
PRINT "What Child is this who, laid to rest on Mary's lap is"
PRINT "sleeping? Whom angels greet with anthems sweet while shepherds"
PRINT "watch are keeping?"
PLAY "T100 O2 E G A MS B. >C< B MN A F# MS D. E F# MN G MS E E. D# E MN F#...."
PLAY "T100 O2 <B....> MS E MN G MS A B. >C< B MN A MS F# D. E F# G F# E D#. C#"
PLAY "T100 O2 D# MN E........ E..."
COLOR 2, 4
CLS
PRINT "What Child is This? REFRAIN"
PRINT "This, this is Christ the King, whom shepherds guard and"
PRINT "angels sing: Haste, Haste to bring Him laud, The Babe, The"
PRINT "Son of Mary!!!"
PLAY "T100 O2 >D.. MS D.. C< B MN A MS F# D.. E F# MN G MS E E.. D# E MN F# MS"
PLAY "T100 O2 D# MN <B> >D.. MS D.. C< B MN A MS F# D.. E F# G F# E D#.. C# D#"
PLAY "T100 O2 MN E........ E..."
END

